/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NelExpandItem {
    /**
    * Is element disabled
    */
    'disabled': boolean;
    /**
    * If element in open state
    */
    'open': boolean;
    /**
    * Text mask
    */
    'size': number;
  }
  interface NelNetworkConnection {
    /**
    * If browser can access network resources
    */
    'available': boolean;
    /**
    * Is element disabled
    */
    'disabled': boolean;
  }
  interface NelTextInput {
    /**
    * Declare if element is disabled
    */
    'disabled': boolean;
    /**
    * Text mask
    */
    'mask': string;
    /**
    * Maximum length
    */
    'maxlength': number;
    /**
    * Minimum length
    */
    'minlength': number;
    /**
    * Text pattern
    */
    'pattern': string;
    /**
    * Text placeholder
    */
    'placeholder': string;
    /**
    * Text value
    */
    'value': string;
  }
  interface NelTextTag {
    /**
    * Main color
    */
    'color': string;
    /**
    * Declare if tag responds to delete/backspace keys
    */
    'deletable': boolean;
    /**
    * Declare if tag is disabled
    */
    'disabled': boolean;
    /**
    * Text label
    */
    'label': string;
    /**
    * Declare if tag can be selected
    */
    'selectable': boolean;
  }
}

declare global {


  interface HTMLNelExpandItemElement extends Components.NelExpandItem, HTMLStencilElement {}
  var HTMLNelExpandItemElement: {
    prototype: HTMLNelExpandItemElement;
    new (): HTMLNelExpandItemElement;
  };

  interface HTMLNelNetworkConnectionElement extends Components.NelNetworkConnection, HTMLStencilElement {}
  var HTMLNelNetworkConnectionElement: {
    prototype: HTMLNelNetworkConnectionElement;
    new (): HTMLNelNetworkConnectionElement;
  };

  interface HTMLNelTextInputElement extends Components.NelTextInput, HTMLStencilElement {}
  var HTMLNelTextInputElement: {
    prototype: HTMLNelTextInputElement;
    new (): HTMLNelTextInputElement;
  };

  interface HTMLNelTextTagElement extends Components.NelTextTag, HTMLStencilElement {}
  var HTMLNelTextTagElement: {
    prototype: HTMLNelTextTagElement;
    new (): HTMLNelTextTagElement;
  };
  interface HTMLElementTagNameMap {
    'nel-expand-item': HTMLNelExpandItemElement;
    'nel-network-connection': HTMLNelNetworkConnectionElement;
    'nel-text-input': HTMLNelTextInputElement;
    'nel-text-tag': HTMLNelTextTagElement;
  }
}

declare namespace LocalJSX {
  interface NelExpandItem extends JSXBase.HTMLAttributes<HTMLNelExpandItemElement> {
    /**
    * Is element disabled
    */
    'disabled'?: boolean;
    /**
    * If element in open state
    */
    'open'?: boolean;
    /**
    * Text mask
    */
    'size'?: number;
  }
  interface NelNetworkConnection extends JSXBase.HTMLAttributes<HTMLNelNetworkConnectionElement> {
    /**
    * If browser can access network resources
    */
    'available'?: boolean;
    /**
    * Is element disabled
    */
    'disabled'?: boolean;
  }
  interface NelTextInput extends JSXBase.HTMLAttributes<HTMLNelTextInputElement> {
    /**
    * Declare if element is disabled
    */
    'disabled'?: boolean;
    /**
    * Text mask
    */
    'mask'?: string;
    /**
    * Maximum length
    */
    'maxlength'?: number;
    /**
    * Minimum length
    */
    'minlength'?: number;
    /**
    * Text pattern
    */
    'pattern'?: string;
    /**
    * Text placeholder
    */
    'placeholder'?: string;
    /**
    * Text value
    */
    'value'?: string;
  }
  interface NelTextTag extends JSXBase.HTMLAttributes<HTMLNelTextTagElement> {
    /**
    * Main color
    */
    'color'?: string;
    /**
    * Declare if tag responds to delete/backspace keys
    */
    'deletable'?: boolean;
    /**
    * Declare if tag is disabled
    */
    'disabled'?: boolean;
    /**
    * Text label
    */
    'label'?: string;
    'onDeleted'?: (event: CustomEvent<any>) => void;
    'onDeleting'?: (event: CustomEvent<any>) => void;
    'onSelected'?: (event: CustomEvent<any>) => void;
    /**
    * Declare if tag can be selected
    */
    'selectable'?: boolean;
  }

  interface IntrinsicElements {
    'nel-expand-item': NelExpandItem;
    'nel-network-connection': NelNetworkConnection;
    'nel-text-input': NelTextInput;
    'nel-text-tag': NelTextTag;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


